server:
  port: 8080
  servlet:
    contextPath: /AcordoCerto
---
spring:
  profiles: local, default
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:{caminho arquivo h2}
    platform: hsqldb
    username: acordo
    password: certo
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: hsql
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect